<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Exercises : Aggregating & Combining Data With pandas: 


---

In [2]:
import pandas as pd

In [3]:
# 6.1 Identifying Missing Data
# We will use the orders table from Super Store for these tasks
orders = pd.read_csv('data/orders.csv')

orders.head(3)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0
2,ES-2018-853948,28/07/2018 00:00,29/07/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,77095.0,1488.0

#### 6.3 GroupBy Insights
Segment the above dataframe and explore aggregate values to answer the following questions

In [9]:
# A. Which discount results in the highest mean ordered quantity?
# Your code here please

orders.groupby('discount')['quantity'].mean(numeric_only=True).sort_values(ascending = False)

discount
0.63    4.589286
0.65    4.541106
0.67    3.947368
0.23    3.691621
0.25    3.637819
0.45    3.628857
0.22    3.624857
0.17    3.616351
0.43    3.605766
0.18    3.587292
0.35    3.579018
0.02    3.572433
0.20    3.559168
0.32    3.548693
0.42    3.546106
0.33    3.544237
0.08    3.541422
0.00    3.485510
0.03    3.481945
0.12    3.480211
0.05    3.449340
0.55    3.445723
0.30    3.441227
0.27    3.437421
0.28    3.435755
0.53    3.432349
0.15    3.407275
0.13    3.396836
0.10    3.389712
0.07    3.369649
0.52    3.353627
0.47    3.314243
0.50    3.285560
0.62    3.267081
0.37    3.246730
0.38    3.206859
0.48    3.129153
0.40    3.111667
0.60    2.972378
0.58    2.851787
0.57    2.843441
Name: quantity, dtype: float64

In [20]:
# NO CODE HERE PLEASE

discount
0.63    4.589286
0.65    4.541106
0.67    3.947368
0.23    3.691688
0.25    3.637796
0.45    3.629135
0.22    3.624779
0.17    3.616351
0.43    3.605606
0.18    3.587096
0.35    3.579037
0.02    3.572521
0.20    3.559066
0.32    3.548776
0.42    3.546444
0.33    3.544198
0.08    3.541474
0.00    3.485676
0.03    3.482138
0.12    3.480322
0.05    3.449331
0.55    3.445424
0.30    3.441305
0.27    3.437534
0.28    3.435605
0.53    3.432594
0.15    3.407333
0.13    3.396777
0.10    3.389850
0.07    3.369472
0.52    3.354398
0.47    3.313827
0.50    3.285641
0.62    3.267081
0.37    3.247030
0.38    3.207138
0.48    3.129519
0.40    3.111864
0.60    2.972697
0.58    2.851787
0.57    2.843441
Name: quantity, dtype: float64

In [10]:
# B. Which product has the highest mean discount applied?
# Your code here please

orders.groupby('product_id')['discount'].mean(numeric_only=True).sort_values(ascending = False)

product_id
OFF-AP-10002899     0.648485
OFF-AP-10004711     0.648333
OFF-AP-10002933     0.648077
OFF-AP-10001197     0.635769
OFF-AP-10002017     0.623214
                      ...
TEC-AC-10002938     0.000000
OFF-PA-10003273     0.000000
TEC-AC-10003469     0.000000
OFF-NOV-10000721    0.000000
OFF-ACC-10002327    0.000000
Name: discount, Length: 10291, dtype: float64

In [21]:
# NO CODE HERE PLEASE

product_id
OFF-AP-10002899     0.648485
OFF-AP-10004711     0.648333
OFF-AP-10002933     0.648077
OFF-AP-10001197     0.635769
OFF-AP-10002017     0.623214
                      ...
TEC-AC-10002938     0.000000
OFF-PA-10003273     0.000000
TEC-AC-10003469     0.000000
OFF-NOV-10000721    0.000000
OFF-ACC-10002327    0.000000
Name: discount, Length: 10291, dtype: float64

In [14]:
# 6.4 Joining DataFrames
# The below example joins our first two dataframes by their shared column, Symbol
openprice = pd.DataFrame({'Symbol': ['AAPL', 'DHR', 'DAL', 'AMZN'], 'OpenPrice': [217.51, 96.54, 51.45, 1703.34]})
wkhigh = pd.DataFrame({'Symbol': ['DAL', 'AMZN', 'AAPL', 'DHR'], '52wkHigh': [60.79, 2050.49, 233.47, 110.11]})
combined = pd.merge(left = openprice, 
                    right = wkhigh,
                    how="left", 
                    left_on='Symbol', 
                    right_on='Symbol')
combined.head()

  Symbol  OpenPrice  52wkHigh
0   AAPL     217.51    233.47
1    DHR      96.54    110.11
2    DAL      51.45     60.79
3   AMZN    1703.34   2050.49

In [15]:
# A. Join the stockname dataframe to our combined result and print the result
stockname = pd.DataFrame({'Symbol': ['AMZN', 'DHR', 'DAL', 'AAPL'], 'Name': ['Amazon', 'Danaher', 'Delta Airlines', 'Apple']})
# complete the below code:
combined= pd.merge(left = combined, right = stockname, how = 'left', on = 'Symbol')


combined.head()

  Symbol  OpenPrice  52wkHigh            Name
0   AAPL     217.51    233.47           Apple
1    DHR      96.54    110.11         Danaher
2    DAL      51.45     60.79  Delta Airlines
3   AMZN    1703.34   2050.49          Amazon

In [17]:
# B. Use the following tables from Super Store
products = pd.read_csv('data/products.csv',encoding='latin')
orders = pd.read_csv('data/orders.csv')
returns = pd.read_csv('data/returns.csv')
regions = pd.read_csv('data/regions.csv')

In [26]:
# i. We want to join the products and orders dataframes.
#    Explore both dataframes to identify the common column between them
# products
# orders
#    Use a left join to combine the tables and save the result table as
#    a dataframe named orders_with_products

# Your code here please:
orders_with_products = pd.merge(left = products, right = orders, how = 'left', on = 'product_id')
orders_with_products.sample(2)

,product_id,category,sub_category,product_name,product_cost_to_consumer,order_id,order_date,ship_date,ship_mode,customer_id,sales,quantity,discount,profit,postal_code,region_id
361454,OFF-BI-10002935,Office Supplies,Binders,"Wilson Jones Binder, Clear",6.24,ES-2019-4011683,16/08/2019 00:00,17/08/2019 00:00,Second Class,JM-15580,24.96,2.0,0.35,0.29,NaN,2898.0
482989,OFF-FA-10001561,Office Supplies,Fasteners,Stockwell Push Pins,1.74,CA-2018-3861944,12/11/2018 00:00,13/11/2018 00:00,Same Day,XP-21865,15.26,7.0,0.23,0.19,NaN,9954.0

In [25]:
# NO CODE HERE PLEASE

,product_id,category,sub_category,product_name,product_cost_to_consumer,order_id,order_date,ship_date,ship_mode,customer_id,sales,quantity,discount,profit,postal_code,region_id
0,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1023854,18/04/2019 00:00,20/04/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.1,0.05,11572.0,5636.0
1,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1802769,02/06/2019 00:00,06/06/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.1,0.05,60653.0,1488.0

In [29]:
# ii. Left join the orders_with_products and returns dataframes
# name the new dataframe orders_with_products_and_returns
# Your code here please

# orders_with_products_and_returns = pd.merge(left = orders_with_products, right = returns, how = 'left', on = 'product_id')

# orders_with_products_and_returns.head()

,product_id,category,sub_category,product_name,product_cost_to_consumer,order_id_x,order_date,ship_date,ship_mode,customer_id,sales,quantity,discount,profit,postal_code,region_id,order_id_y,return_date,return_quantity,reason_returned
0,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1023854,18/04/2019 00:00,20/04/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.10,0.05,11572.0,5636.0,NaN,NaN,NaN,NaN
1,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1802769,02/06/2019 00:00,06/06/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.10,0.05,60653.0,1488.0,NaN,NaN,NaN,NaN
2,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-2227798,29/04/2019 00:00,04/05/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.10,0.05,90049.0,4553.0,NaN,NaN,NaN,NaN
3,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-3889,15/05/2019 00:00,19/05/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.10,0.05,94122.0,4553.0,NaN,NaN,NaN,NaN
4,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,IZ-2019-1054400,19/09/2019 00:00,20/09/2019 00:00,Standard Class,TB-21190,53.04,1.0,0.35,0.28,10035.0,5636.0,NaN,NaN,NaN,NaN

In [26]:
# NO CODE HERE PLEASE

,product_id_x,category,sub_category,product_name,product_cost_to_consumer,order_id,order_date,ship_date,ship_mode,customer_id,sales,quantity,discount,profit,postal_code,region_id,return_date,return_quantity,reason_returned,product_id_y
0,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1023854,18/04/2019 00:00,20/04/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.1,0.05,11572.0,5636.0,NaN,NaN,NaN,NaN
1,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1802769,02/06/2019 00:00,06/06/2019 00:00,Standard Class,PH-18790,106.08,2.0,0.1,0.05,60653.0,1488.0,NaN,NaN,NaN,NaN

In [30]:
regions

,region_id,country_code,country,region,sub_region,salesperson
0,45585,TH,Thailand,APAC,South-Eastern Asia,Fei Hong
1,4364,PA,Panama,Americas,Central America,Anna Andreadi
2,7530,UA,Ukraine,EMEA,Eastern Europe,Giulietta Dortch
3,28804,KR,South Korea,APAC,Eastern Asia,Wang Xiu Ying
4,4119,SK,Slovakia,EMEA,Eastern Europe,Giulietta Dortch
...,...,...,...,...,...,...
144,15271,UG,Uganda,EMEA,Africa,Deborah Brumfield
145,59565,SO,Somalia,EMEA,Africa,Deborah Brumfield
146,5003,GT,Guatemala,Americas,Central America,Anna Andreadi
147,38912,AM,Armenia,EMEA,Southern Europe,Giulietta Dortch
148,95296,ET,Ethiopia,EMEA,Africa,Deborah Brumfield

In [32]:
# iii. Finally, add the region data to our combined dataframe
# do inner join of the previous dataframe with `regions` dataframe 
# name the new dataframe orders_with_products_and_returns_and_regions

# Your code here please
orders_with_products_and_returns_and_regions = pd.merge(left = orders_with_products_and_returns,
                                                        right = regions, how = 'inner', on = 'region_id')
orders_with_products_and_returns_and_regions.head()

,product_id,category,sub_category,product_name,product_cost_to_consumer,order_id_x,order_date,ship_date,ship_mode,customer_id,...,region_id,order_id_y,return_date,return_quantity,reason_returned,country_code,country,region,sub_region,salesperson
0,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1023854,18/04/2019 00:00,20/04/2019 00:00,Standard Class,PH-18790,...,5636.0,NaN,NaN,NaN,NaN,US,United States,Americas,East United States,Kelly Williams
1,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1802769,02/06/2019 00:00,06/06/2019 00:00,Standard Class,PH-18790,...,1488.0,NaN,NaN,NaN,NaN,US,United States,Americas,Central United States,Annelise Williams
2,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-2227798,29/04/2019 00:00,04/05/2019 00:00,Standard Class,PH-18790,...,4553.0,NaN,NaN,NaN,NaN,US,United States,Americas,West United States,Matt Collister
3,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-3889,15/05/2019 00:00,19/05/2019 00:00,Standard Class,PH-18790,...,4553.0,NaN,NaN,NaN,NaN,US,United States,Americas,West United States,Matt Collister
4,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,IZ-2019-1054400,19/09/2019 00:00,20/09/2019 00:00,Standard Class,TB-21190,...,5636.0,NaN,NaN,NaN,NaN,US,United States,Americas,East United States,Kelly Williams

In [27]:
# NO CODE HERE PLEASE

,product_id_x,category,sub_category,product_name,product_cost_to_consumer,order_id,order_date,ship_date,ship_mode,customer_id,...,region_id,return_date,return_quantity,reason_returned,product_id_y,country_code,country,region,sub_region,salesperson
0,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1023854,18/04/2019 00:00,20/04/2019 00:00,Standard Class,PH-18790,...,5636.0,NaN,NaN,NaN,NaN,US,United States,Americas,East United States,Kelly Williams
1,FUR-ADV-10000002,Furniture,Furnishings,"Advantus Photo Frame, Duo Pack",53.04,CG-2019-1802769,02/06/2019 00:00,06/06/2019 00:00,Standard Class,PH-18790,...,1488.0,NaN,NaN,NaN,NaN,US,United States,Americas,Central United States,Annelise Williams

In [34]:
# iv. Let's use this combined dataframe to determine the salesperson generating the most profit
# Your code here please

orders_with_products_and_returns_and_regions.groupby('salesperson')['profit'].sum()

salesperson
Agwe Aristide         466397.68
Anna Andreadi        2080307.79
Annelise Williams     383529.46
Beatrice Top         1269690.25
Chuck Magee          1228905.07
Deborah Brumfield    1221766.98
Fei Hong              910675.57
Giulietta Dortch     1090699.09
Kelly Williams        644325.74
Luca Tremblay         109713.35
Matt Collister        783861.71
Nicole Hansen         361302.80
Nora Preis            942992.67
Scott Smith           444276.96
Wang Xiu Ying         538270.38
Name: profit, dtype: float64

In [28]:
# NO CODE HERE PLEASE

salesperson
Anna Andreadi        266414.90
Chuck Magee          158196.88
Giulietta Dortch     154333.77
Deborah Brumfield    146810.27
Beatrice Top         142068.74
Nora Preis           120771.03
Fei Hong             107031.85
Matt Collister        91316.88
Wang Xiu Ying         83931.66
Kelly Williams        83576.98
Scott Smith           55180.07
Nicole Hansen         54560.14
Annelise Williams     49799.81
Agwe Aristide         45843.91
Luca Tremblay         13722.45
Name: profit, dtype: float64